### ISSUE TITLE
Cassowary.js 

### ISSUE THREAD

**Issue by d4tocchini** [babelsberg/babelsberg-js#20]
Howdy, this is awesomely ambitious!  

I'm the creator of http://gridstylesheets.org/ and a contributor to https://github.com/slightlyoff/cassowary.js, wondering if you guys considered that Cassowary port & reasons for / against?

**Comment by timfel** [comment]
At the time we started Babelsberg, it was exclusively developed in Lively, which already included a port of Greg Badros' JS implementation to Lively's module system. But we are in the process of splitting this project up into packages for each of the solvers, the COP implementation, the Interpreter, and Babelsberg itself. For that we are already discussing using other Cassowary implementations, but we'll have to check if they work (we had to change a couple of things from Greg's implementation)

**Comment by d4tocchini** [comment]
Curious what you had to change.  I've found the edit constraints particularly obtuse at scale...

**Comment by timfel** [comment]
Alan Borning is currently visiting, and we've got a few students working on making edit constraints work automatically by watching how the solver is used and automatically applying their optimizations for incremental resolving

**Comment by timfel** [comment]
For some experiments, we (for now) included 3 different implementations of Cassowary: the original JS port done by Greg, the one from slightlyoff/cassowary.js, as well as an Emscripten-based port of Rhea, which is a Cassowary implementation in C++. Curiously, the Emscripten version is often the slowest.
